apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "leaksignal.name" . }}
  labels:
    app: {{ include "leaksignal.name" . }}
    {{- include "leaksignal.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "leaksignal.name" . }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "leaksignal.name" . }}
      {{- include "leaksignal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: {{ include "leaksignal.name" . }}
        ls-native: excluded
        {{- include "leaksignal.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      priorityClassName: leaksignal-operator
      {{- with .Values.schedulerName }}
      schedulerName: "{{ . }}"
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: ganesha-configure
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        env:
        - name: INIT
          value: "1"
        volumeMounts:
        - name: ganesha-conf
          mountPath: /etc/ganesha
      containers:
      - name: ganesha
        image: {{ .Values.nfsImage.repository }}:{{ .Values.nfsImage.tag | default "5.9" }}
        imagePullPolicy: Always
        ports:
        - containerPort: 2049
          name: nfs
        - containerPort: 111
          name: nfs-rpc
        {{- with .Values.nfsResources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: proxy-store
          mountPath: /exports
        - name: ganesha-conf
          mountPath: /etc/ganesha
      # - name: unfs3
      #   image: {{ .Values.unfsImage.repository }}:{{ .Values.unfsImage.tag | default "5.9" }}
      #   imagePullPolicy: Always
      #   ports:
      #   - containerPort: 2049
      #     name: nfs
      #   - containerPort: 111
      #     name: nfs-rpc
      #   {{- with .Values.nfsResources }}
      #   resources:
      #     {{- toYaml . | nindent 10 }}
      #   {{- end }}
      #   volumeMounts:
      #   - name: proxy-store
      #     mountPath: /exports
      - name: operator
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: webhook-tls
        env:
        - name: RUST_LOG
          value: TRACE
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: proxy-store
          mountPath: /proxy
{{ if and .Values.imageCredentials .Values.imageCredentials.username .Values.imageCredentials.password }}
      imagePullSecrets:
      - name: {{ include "leaksignal.name" . }}-image-secret
{{ end }}
      {{ if .Values.rbacEnabled }}
      serviceAccountName: {{ include "leaksignal.name" . }}
      {{ end }}
      volumes:
      - name: proxy-store
        emptyDir: {}
      - name: ganesha-conf
        emptyDir: {}
