apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: leaksignal-operator
  labels:
    app: leaksignal-operator
    {{- include "leaksignal.labels" . | nindent 4 }}
spec:
  serviceName: leaksignal-operator
  replicas: 1
  selector:
    matchLabels:
      app: leaksignal-operator
      {{- include "leaksignal.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: leaksignal-operator
        ls-native: excluded
        {{- include "leaksignal.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      priorityClassName: leaksignal-operator
      {{- with .Values.schedulerName }}
      schedulerName: "{{ . }}"
      {{- end }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.hostAliases }}
      hostAliases:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: operator
        image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        ports:
        - containerPort: 8443
          name: webhook-tls
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
{{ if and .Values.imageCredentials .Values.imageCredentials.username .Values.imageCredentials.password }}
      imagePullSecrets:
      - name: leaksignal-operator-image-secret
{{ end }}
      {{ if .Values.rbacEnabled }}
      serviceAccountName: leaksignal-operator
      {{ end }}
