apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: leaksignal-operator
  labels:
    app: leaksignal-operator
    {{- include "leaksignal.labels" . | nindent 4 }}
preemptionPolicy: PreemptLowerPriority
value: {{ .Values.priority }}
globalDefault: false
