{{ if .Values.rbacEnabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: leaksignal-operator
  labels:
    app: leaksignal-operator
    {{- include "leaksignal.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: leaksignal-operator
  labels:
    app: leaksignal-operator
    {{- include "leaksignal.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - pods
  verbs:
  - list
  - get
  - delete
  - patch
  - update
- apiGroups: [""]
  resources:
  - namespaces
  - services
  verbs:
  - list
  - get
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  verbs:
  - list
  - get
  - patch
  - update
  - create
  - replace
- apiGroups:
  - leaksignal.com
  resources:
  - cluster-leaksignal-istios
  - leaksignal-istios
  - leaksignal-network-taps
  verbs:
  - get
  - watch
  - list
  - patch
- apiGroups:
  - networking.istio.io
  resources:
  - envoyfilters
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete
  resourceNames:
  - z-leaksignal-operator
{{ if .Values.rbacArgoRollout }}
- apiGroups: ["argoproj.io"]
  resources:
  - rollouts
  verbs:
  - list
  - get
  - patch
  - update
{{ end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: leaksignal-operator
  labels:
    app: leaksignal-operator
    {{- include "leaksignal.labels" . | nindent 4 }}
rules:
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - watch
  - list
  - create
  - update
  - patch
  - delete

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: leaksignal-operator
  labels:
    app: leaksignal-operator
    {{- include "leaksignal.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: leaksignal-operator
subjects:
- kind: ServiceAccount
  name: leaksignal-operator
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: leaksignal-operator
  labels:
    app: leaksignal-operator
    {{- include "leaksignal.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: leaksignal-operator
subjects:
- kind: ServiceAccount
  name: leaksignal-operator
  namespace: {{ .Release.Namespace }}

{{ end }}