apiVersion: v1
kind: Service
metadata:
  name: leaksignal-operator
  labels:
    app: leaksignal-operator
    {{- include "leaksignal.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: leaksignal-operator
    {{- include "leaksignal.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
      name: webhook-tls
