apiVersion: v1
kind: Service
metadata:
  name: {{ include "leaksignal.name" . }}
  labels:
    app: {{ include "leaksignal.name" . }}
    {{- include "leaksignal.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app: {{ include "leaksignal.name" . }}
    {{- include "leaksignal.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
      name: webhook-tls
    - protocol: TCP
      port: 2049
      targetPort: 2049
      name: proxy-nfs
    - protocol: TCP
      port: 111
      targetPort: 2049
      name: proxy-rpcbind
